services:

  l2_postgres:
    image: postgres:latest
    container_name: Linage2_towns
    restart: always
    environment:
      POSTGRES_USER: ${MY_USER}
      POSTGRES_PASSWORD: ${MY_PASSWORD}
      POSTGRES_DB: L2_towns
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./L2_towns_dump.sql:/docker-entrypoint-initdb.d/dump.sql

  l2_app:
    build: .
    container_name: l2_calculator
    depends_on:
      - l2_postgres
    environment:
      DB_HOST: l2_postgres
      DB_USER: ${MY_USER}
      DB_PASSWORD: ${MY_PASSWORD}
      DB_PORT: 5432

    ports:
      - "2137:2137"

volumes:
  postgres_data:
