services:

  l2_postgres:
    image: postgres:16
    container_name: Lineage2_towns
    restart: always
    environment:
      POSTGRES_USER: ${MY_USER}
      POSTGRES_PASSWORD: ${MY_PASSWORD}
      POSTGRES_DB: L2_towns
    ports:
      - "5432:5432"
    volumes:
      - ./L2_towns_dump.sql:/docker-entrypoint-initdb.d/L2_towns_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MY_USER} -d ${POSTGRES_DB:-L2_towns}"]
      interval: 5s
      timeout: 2s
      retries: 10

  l2_app:
    build: ./Lineage2Calculator
    container_name: l2_calculator
    depends_on:
      - l2_postgres
    env_file:
      - .env
    environment:
      DB_HOST: l2_postgres
      DB_USER: ${MY_USER}
      DB_PASSWORD: ${MY_PASSWORD}
      DB_PORT: 5432
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"