spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/L2_towns
    username: ${MY_USER}
    password: ${MY_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
